Jenkinsfile

added simple Jenkinsfile according to recommendations here: https://github.com/jenkinsci/electricflow-plugin/pulls

NTVEPLUGIN-145 - added simple Jenkinsfile according to recommendations

---

.gitignore
pom.xml
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowClient.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowRunProcedure.java
src/main/java/org/jenkinsci/plugins/electricflow/data/CloudBeesFlowArtifactData.java
src/main/java/org/jenkinsci/plugins/electricflow/data/CloudBeesFlowBuildData.java
src/main/java/org/jenkinsci/plugins/electricflow/data/CloudBeesFlowPipelineData.java
src/main/java/org/jenkinsci/plugins/electricflow/data/CloudBeesFlowSCMData.java
src/main/java/org/jenkinsci/plugins/electricflow/data/CloudBeesFlowTestResultData.java
src/main/java/org/jenkinsci/plugins/electricflow/extension/CloudBeesFlowArtifact.java
src/main/java/org/jenkinsci/plugins/electricflow/extension/CloudBeesFlowBaseExtension.java
src/main/java/org/jenkinsci/plugins/electricflow/extension/CloudBeesFlowPipeline.java
src/main/java/org/jenkinsci/plugins/electricflow/extension/CloudBeesFlowSCM.java
src/main/java/org/jenkinsci/plugins/electricflow/extension/CloudBeesFlowTestResult.java
src/main/java/org/jenkinsci/plugins/electricflow/extension/impl/CloudBeesFlowPipelineRest.java
src/main/java/org/jenkinsci/plugins/electricflow/extension/impl/CloudBeesFlowSCMGit.java
src/main/java/org/jenkinsci/plugins/electricflow/extension/impl/CloudBeesFlowTestResultJUnit.java
src/main/java/org/jenkinsci/plugins/electricflow/integration/ElectricFlowChangeSet.java
src/main/java/org/jenkinsci/plugins/electricflow/integration/ElectricFlowGitChangeSet.java
src/main/java/org/jenkinsci/plugins/electricflow/rest/AbstractAPIActionHandler.java
src/main/java/org/jenkinsci/plugins/electricflow/rest/CloudBeesFlowAPIHandler.java

Creating a new baseline branch to merge ongoing changes for core flow integration

Core flow integration playground merge

---

src/main/java/org/jenkinsci/plugins/electricflow/event/ElectricFlowBuildWatcher.java

Add logging for the failed associate ciBuildData call in the BuildWatcher

NTVEPLUGIN-281

---

Jenkinsfile

Fixing build.recommendedConfigurations() broke CI builds

NTVEPLUGIN-294. Fixing CI builds

---

specs/src/test/groovy/com/electriccloud/plugin/spec/nativeplugin/AssociateBuildToReleaseSuite.groovy
specs/src/test/groovy/com/electriccloud/plugin/spec/nativeplugin/TriggerPipelineSuite.groovy
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowAssociateBuildToRelease.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowClient.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher.java

AssociateBuildToRelease - Release
TriggerPipeline - Project, Pipeline

NTVEPLUGIN-196 Negative cases handling

---

specs/src/test/groovy/com/electriccloud/plugin/spec/core/artifacts/Artifact.groovy
specs/src/test/groovy/com/electriccloud/plugin/spec/nativeplugin/RunProcedureSuite.groovy
specs/src/test/groovy/com/electriccloud/plugin/spec/nativeplugin/TriggerPipelineSuite.groovy
specs/src/test/groovy/com/electriccloud/plugin/spec/nativeplugin/TriggerReleaseSuite.groovy
specs/src/test/resources/dsl/RunAndWait/runAndWaitPipeline.dsl
specs/src/test/resources/dsl/RunAndWait/runAndWaitProcedure.dsl
specs/src/test/resources/dsl/RunAndWait/runAndWaitRelease.dsl
specs/src/test/resources/jenkinsXMLs/Readme.md
specs/src/test/resources/jenkinsXMLs/RunPipelineRunAndWaitPipeline.xml
specs/src/test/resources/jenkinsXMLs/RunProcedureRunAndWaitPipeline.xml
specs/src/test/resources/jenkinsXMLs/TriggerReleaseRunAndWaitPipeline.xml

https://cloudbees.atlassian.net/browse/NTVEPLUGIN-370
. Release 1.1.17 - QA. Add new automation tests

Ntveplugin 370

---

README.md

NTVEPLUGIN-438 - updated release notes

---

src/main/java/org/jenkinsci/plugins/electricflow/action/CloudBeesCDPBABuildDetails.java
src/main/java/org/jenkinsci/plugins/electricflow/models/CIBuildDetail.java

This change is required for SDA plugin to show up to date values.
- [ x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [ x] Please describe what you did

Rebranding: renaming triggerSource and associationType enums

---

pom.xml
src/main/java/org/jenkinsci/plugins/electricflow/rest/ElectricFlowEFRunAPIAction.java

This merges back https://github.com/jenkinsci/electricflow-plugin/releases/tag/cloudbees-flow-1.1.22 with https://www.jenkins.io/security/advisory/2021-04-21/#SECURITY-2309 into `master`.
Please merge using merge commit, NOT using squash or rebase, to retain the release commits on the master branch.

Merge release 1.1.22

---

src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowTriggerRelease.java

Added proper parameters handling for TriggerRelease procedure

---

pom.xml
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowDeployApplication.java
src/main/java/org/jenkinsci/plugins/electricflow/FileHelper.java
src/main/java/org/jenkinsci/plugins/electricflow/Utils.java

- [] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Swithed code to hudson.DirScanner, fixed warning

---

pom.xml
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowTriggerRelease.java

Final fix for empty stages in trigger release post build action

---

src/main/java/org/jenkinsci/plugins/electricflow/FileHelper.java

NTVEPLUGIN-451 - fix for publish artifacts when using agent

---

README.md

NTVEPLUGIN-462 - 1.1.25 release notes

---

README.md

NTVEPLUGIN-462 - fixed typos in readme

---

pom.xml
src/main/java/org/jenkinsci/plugins/electricflow/CloudBeesFlowCallRestApiStep.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowAssociateBuildToRelease.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowDeployApplication.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowGenericRestApi.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowPublishApplication.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowRunProcedure.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowTriggerRelease.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowUploadArtifactPublisher.java
src/main/java/org/jenkinsci/plugins/electricflow/action/CloudBeesCDPBABuildDetails.java
src/main/java/org/jenkinsci/plugins/electricflow/envvars/VariableInjectionAction.java
src/main/java/org/jenkinsci/plugins/electricflow/extension/impl/CloudBeesFlowPipelineRest.java
src/main/java/org/jenkinsci/plugins/electricflow/rest/ElectricFlowEFRunAPIActionFactory.java

Cleanup dependency declarations
pretty much obsoletes every other PR with the exception of #149 (which is a bump of the only directly bundled library)

refresh parent to enable compatability testing with recent jenkins versions

---

src/main/java/org/jenkinsci/plugins/electricflow/Configuration.java
src/main/java/org/jenkinsci/plugins/electricflow/Credential.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowAssociateBuildToRelease.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowClient.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowDeployApplication.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowRunProcedure.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowTriggerRelease.java
src/main/java/org/jenkinsci/plugins/electricflow/Utils.java
src/main/java/org/jenkinsci/plugins/electricflow/credentials/CredentialHandler.java
src/main/java/org/jenkinsci/plugins/electricflow/credentials/ItemCredentialHandler.java
src/main/java/org/jenkinsci/plugins/electricflow/credentials/RunCredentialHandler.java
src/main/java/org/jenkinsci/plugins/electricflow/event/ElectricFlowBuildWatcher.java
src/main/java/org/jenkinsci/plugins/electricflow/factories/ElectricFlowClientFactory.java
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowGlobalConfiguration/config.jelly
src/test/java/BasicUnitTestsWithJenkins.java
src/test/java/org/jenkinsci/plugins/electricflow/ElectricFlowBuildWatcherTest.java
src/test/java/org/jenkinsci/plugins/electricflow/test/Utils.java

- added support of cloudbees cd tokens which now can be configured as stored credential (secret text) for main or override configurations;
- improved handling of override credentials;
- fixed handling of stages in Trigger Release
Check up:

BEE-24008 - support for using CD tokens + minor fixes (including BEE-19963 fix for Trigger Release)

---

src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowGlobalConfiguration/config.jelly

BEE-24008 - typo

---

README.md

-- Added a new section to describe how to configure an SSO session ID token for the plugin. 
-- [BEE-27844](https://cloudbees.atlassian.net/browse/BEE-27844)
-- Content needs a technical content review to ensure the task is accurately described.

[BEE-27844] Added Configuring an SSO session ID token instructions

---

README.md

-- The description of supported Stored Credentials was updated. 
-- [BEE-27844](https://cloudbees.atlassian.net/browse/BEE-27844)
-- Content needs a technical content review to ensure the task is accurately described.

[BEE-27844] Change description of Stored Credential support

---

README.md

BEE-24019 - 1.1.28 release notes

---

pom.xml

BEE-28506 - fixed dependencies

---

README.md

BEE-28405 - 1.1.29 release notes

---

src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowClient.java
src/test/java/org/jenkinsci/plugins/electricflow/MultipartUtilityTest.java

BEE-29908 Native Jenkins plugin unable to connect to recent 2023.01 RC

---

README.md

-- Added release notes for 1.1.30 release 
-- [BEE-30060](https://cloudbees.atlassian.net/browse/BEE-30060)
- [N/A] Link to relevant pull requests, esp. upstream and downstream changes
- [N/A] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[BEE-30060_relnotes] Add 1.1.30 release notes

---

src/main/java/org/jenkinsci/plugins/electricflow/Configuration.java
src/test/java/org/jenkinsci/plugins/electricflow/ConfigurationAsCodeTest.java
src/test/resources/casc/configuration-as-code-cred-id.yml

Fixed configuration as code issue with new credentials id

SECO-2604 - fixed configuration as code issue with new credentials id

---

README.md

-- For CD/RO v2023.02.0, it is required to upgrade to 1.1.30 version of plugin because CGI scripts were removed. I added a section to communicate this to users. 
-- [BEE-30060](https://cloudbees.atlassian.net/browse/BEE-30060)
- [N/A] Link to relevant pull requests, esp. upstream and downstream changes
- [N/A] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[BEE-30060] Added CloudBees CDRO version dependencies

---

src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowClient.java

updated usage of token for connection to CD

Updated connection configuration

---

src/test/java/org/jenkinsci/plugins/electricflow/ConfigurationAsCodeTest.java

Added extra tests for configuration as code export checks

Added extra tests for configuration as code export checks

---

src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowClient.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher.java
src/main/java/org/jenkinsci/plugins/electricflow/Utils.java
src/main/java/org/jenkinsci/plugins/electricflow/models/cdrestdata/jobs/StageResponseData.java
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher/config.jelly

Added stage options for run pipeline (based on trigger release stage options)

Added stage options for run pipeline (based on trigger release stage options)

---

src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher.java
src/main/java/org/jenkinsci/plugins/electricflow/Utils.java
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher/config.jelly

fixes according to QA results: fixed run pipeline with compare table

BEE-27642 - fixes for run pipeline with compare table

---

src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowClient.java
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher.java

BEE-27642 - minor fixes for run pipeline stages

BEE-27642 - minor fixes

---

README.md

Jira: [BEE-28958](https://cloudbees.atlassian.net/browse/BEE-28958)
Added missing release notes for v1.1.31 and v1.132.

[BEE-28958] Add release notes for v1.1.31 and v1.1.32

---

README.md

Jira: [BEE-39904](https://cloudbees.atlassian.net/browse/BEE-39904)
Applied CloudBees style guide to release notes.

[BEE-39904] Copy edit changelog

---

README.md
pom.xml
src/main/resources/index.jelly

Jira: [BEE-40361](https://cloudbees.atlassian.net/browse/BEE-40361)
Updated the plugin description in the docs and the Jenkins plugin description.
- [N/A]  Ensure you have provided tests - that demonstrates feature works or fixes the issue

[BEE-40361] Update plugin docs description

---

src/main/resources/org/jenkinsci/plugins/electricflow/CloudBeesFlowCallRestApiStep/help-body.html
src/main/resources/org/jenkinsci/plugins/electricflow/CloudBeesFlowCallRestApiStep/help-envVarNameForResult.html
src/main/resources/org/jenkinsci/plugins/electricflow/CloudBeesFlowCallRestApiStep/help-httpMethod.html
src/main/resources/org/jenkinsci/plugins/electricflow/CloudBeesFlowCallRestApiStep/help-parameters.html
src/main/resources/org/jenkinsci/plugins/electricflow/CloudBeesFlowCallRestApiStep/help-urlPath.html
src/main/resources/org/jenkinsci/plugins/electricflow/CloudBeesFlowCallRestApiStep/help.html
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowGenericRestApi/help-body.html
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowGenericRestApi/help-envVarNameForResult.html
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowGenericRestApi/help-httpMethod.html
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowGenericRestApi/help-parameters.html
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowGenericRestApi/help-urlPath.html
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowGenericRestApi/help.html

- [ :white_check_mark: ] Make sure you are opening from a topic/feature/bugfix branch (right side) and not your main branch!
- [ :white_check_mark:]  Ensure that the pull request title represents the desired changelog entry
- [ :white_check_mark:]  Please describe what you did: 
- Updated HTML tool tips for [Calling CloudBees CD REST API](https://plugins.jenkins.io/electricflow/#plugin-content-calling-cloudbees-cd-rest-api) procedure. Updated for Configuration and Pipeline Syntax.
- [ :white_check_mark:]  Link to relevant issues in GitHub or Jira: [BEE-45137](https://cloudbees.atlassian.net/browse/BEE-45137)
- [ :white_check_mark:]  Link to relevant pull requests, esp. upstream and downstream changes:
- https://github.com/jenkinsci/electricflow-plugin/pull/356 
- [N/A]  Ensure you have …

[BEE-45137_UI] Update UI tools tips for REST API calls

---

README.md

- [ :white_check_mark: ] Make sure you are opening from a topic/feature/bugfix branch (right side) and not your main branch!
- [ :white_check_mark:]  Ensure that the pull request title represents the desired changelog entry
- [ :white_check_mark:]  Please describe what you did: 
- Updated the docs for **Supported Post Build Actions** > **Calling CloudBees CD REST API** to include CD/RO docs and Swagger UI references. 
- Added admonition for parameters with `request=sendReportingData`. 
- [ :white_check_mark:]  Link to relevant issues in GitHub or Jira: [BEE-45137](https://cloudbees.atlassian.net/browse/BEE-45137)
- [ :white_check_mark:]  Link to relevant pull requests, esp. upstream and downstream changes:
- https://github.com/jenkinsci/electricflow-plugin/pull/357 
- [N/A]  Ensure you …

[BEE-45137_docs] Update Call API post build docs

---

README.md

- [ :white_check_mark: ] Make sure you are opening from a topic/feature/bugfix branch (right side) and not your main branch!
- [ :white_check_mark:]  Ensure that the pull request title represents the desired changelog entry
- [ :white_check_mark:]  Please describe what you did: 
- Fixed: 
- Grammatical errors
- Punctuation errors
- CloudBees CD/RO references
- UI element references  
- [ :white_check_mark:]  Link to relevant issues in GitHub or Jira: [BEE-45137](https://cloudbees.atlassian.net/browse/BEE-45137)
- [ :white_check_mark:]  Link to relevant pull requests, esp. upstream and downstream changes:
- https://github.com/jenkinsci/electricflow-plugin/pull/356 
- [N/A]  Ensure you have provided tests - that demonstrates feature works or fixes the issue

[BEE-45137_docs] Fix documentation errors

---

README.md

Jira: 
- [ :white_check_mark: ] Make sure you are opening from a topic/feature/bugfix branch (right side) and not your main branch!
- [ :white_check_mark:]  Ensure that the pull request title represents the desired changelog entry
- [ :white_check_mark:]  Please describe what you did: 
- Add release notes for v1.1.34
- [ :white_check_mark:]  Link to relevant issues in GitHub or Jira: [BEE-45792](https://cloudbees.atlassian.net/browse/BEE-45792)
- [N/A]   Link to relevant pull requests, esp. upstream and downstream changes
- [N/A]  Ensure you have provided tests - that demonstrates feature works or fixes the issue

[BEE-45792] Add release notes for v1.1.34

---

pom.xml
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowTriggerRelease.java

Fixed an issue that occurred when the *Stage to start* not specified in *Trigger Release* post-build action.

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/electricflow/ElectricFlowClient.java

Updating the parent pom so the plugin is getting the new Jenkins Test Harness and is still validated with PCT.
The new parent pom required to bump Jenkins version requirement and to fix a bit of code.
Closes #355.
Closes #343.
Ran `mvn verify` without problem.

Bump parent pom from 4.51 to 4.58

---

README.md

- [💯] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [💯] Ensure that the pull request title represents the desired changelog entry
- [💯] Please describe what you did -> Updated release notes for last release.
- [/] Link to relevant issues in GitHub or Jira- Hotfix. 
- [N/A] Link to relevant pull requests, esp. upstream and downstream changes
- [N/A] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Update release notes for 1.1.37 release

---

README.md
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher/config.jelly
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher/help-runAllStages.html
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher/help-stagesToRun.html
src/main/resources/org/jenkinsci/plugins/electricflow/ElectricFlowPipelinePublisher/help-startingStage.html

Jira: [CDRO-952](https://cloudbees.atlassian.net/browse/CDRO-952)

[CDRO-952] Update tool tips for stage options

---

README.md

PR to update the version in the README

Updating the release date for version 1.1.39
